version: '2'
services:
  db:
    image: 'mysql:5.7'
    command: mysqld --user=root --verbose
    restart: always
    volumes:
      - /opt/data/mysql/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Wzj_mysql01
      - MYSQL_PASSWORD=Wzj_mysql01
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=db_user

#  netdisk:
#    image: nextcloud
#    ports:
#      - 5800:80
#    depends_on:
#      - db
#    volumes:
#      - /opt/data/nextcloud/html:/var/www/html
#      - /opt/data/nextcloud/data:/var/www/html/data
#      - /opt/data/nextcloud/config:/var/www/html/config
#    restart: always

#  discuz:
#    image: skyzhou/docker-discuz
#    ports:
#      - 80:80
#    depends_on:
#      - db
#    environment:
#      - MYSQL_PORT_3306_TCP=db:3306
#      - DISCUZ_DB_PASSWORD=Wzj_mysql01
#      - MYSQL_ENV_MYSQL_ROOT_PASSWORD=Wzj_mysql01
#      - DISCUZ_DB_USER=db_user
#      - DISCUZ_DB_NAME=discuz
#    restart: always

  movie:
    image: zjtech/applecms
    ports:
      - 80:80
    depends_on:
      - db
    restart: always

  gateway:
    image: nginx
    ports:
      - 443:443
      - 5808:80
    depends_on:
      - movie
    #links:
    #  - movie:movie
    volumes:
      - '/opt/github/myVm/gateway:/opt/nginx/conf/'
      - '/opt/github/myVm/gateway/nginx.conf:/etc/nginx/nginx.conf'  

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: db_user
      MONGO_INITDB_ROOT_PASSWORD: Wzj_mysql01
    volumes:
    - '/opt/data/mongodb:/data/db'

  admin-mongo:
    image: mrvautin/adminmongo
    # restart: always
    #ports:
    #- '5803:1234'

  tracker1:
    image: ygqygq2/fastdfs-nginx
    command: tracker
    network_mode: host
    volumes:
    - /opt/data/fdfs/tracker1:/var/fdfs
    - /opt/data/fdfs/tracker1/logs/:/var/fdfs/logs/

  storage1:
    image: ygqygq2/fastdfs-nginx
    command: storage
    network_mode: host
    volumes:
    - /opt/data/fdfs/g1_storage1:/var/fdfs
    environment:
    - TRACKER_SERVER=172.16.0.192:22122
    - GROUP_NAME=group1
    depends_on:
    - tracker1
   
  image-service:
    image: jeven2016/image-service
    #ports:
    #- '5806:5806'
    environment:
    - tracker=172.16.0.192:22122
    - mongo_host=mongo  





