version: '2'
services:
  db:
    image: 'mysql:5.7'
    command: mysqld --user=root --verbose
    restart: always
    volumes:
      - /opt/data/mysql/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Wzj_mysql01
      - MYSQL_PASSWORD=Wzj_mysql01
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=db_user

  netdisk:
    image: nextcloud
    ports:
      - 5800:80
    depends_on:
      - db
    volumes:
      - /opt/data/nextcloud/html:/var/www/html
      - /opt/data/nextcloud/data:/var/www/html/data
      - /opt/data/nextcloud/config:/var/www/html/config
    restart: always
