---
version: '2'
services:
  nginx:
    image: nginx
    network_mode: host
    extra_hosts:
      - "nginx:127.0.0.1"
    volumes:
      - '/root/Desktop/workspace/projects/TestGradle/docker-yml/nginx/:/opt/nginx/conf/'
      - '/root/Desktop/workspace/projects/TestGradle/docker-yml/nginx/nginx.conf:/etc/nginx/nginx.conf'
